--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ricky/repos/pictures/Wallpapers/purple_neon/3.jpg"

-- Special
background="#0B050F"
foreground="#a5c3ef"
cursor="#a5c3ef"

-- Colors
color0="#0B050F"
color1="#6C1994"
color2="#5B58DD"
color3="#9717AA"
color4="#A920CC"
color5="#E220E7"
color6="#C656E0"
color7="#a5c3ef"
color8="#7388a7"
color9="#6C1994"
color10="#5B58DD"
color11="#9717AA"
color12="#A920CC"
color13="#E220E7"
color14="#C656E0"
color15="#a5c3ef"
