# Shell variables
# Generated by 'wal'
wallpaper="/home/ricky/repos/pictures/Wallpapers/purple_neon/3.jpg"

# Special
background='#0B050F'
foreground='#a5c3ef'
cursor='#a5c3ef'

# Colors
color0='#0B050F'
color1='#6C1994'
color2='#5B58DD'
color3='#9717AA'
color4='#A920CC'
color5='#E220E7'
color6='#C656E0'
color7='#a5c3ef'
color8='#7388a7'
color9='#6C1994'
color10='#5B58DD'
color11='#9717AA'
color12='#A920CC'
color13='#E220E7'
color14='#C656E0'
color15='#a5c3ef'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
